name: nations_assets
description: localization assets for nations - queen support for localization in flutter, part of queen
version: 0.0.1
homepage: https://github.com/FlutterQueen/nations_assets
issue_tracker: https://github.com/FlutterQueen/nations_assets/issues
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

# dependencies:
#   flutter:
#     sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
