name: nations_assets
description: localization assets for nations - part of queen
version: 0.0.4
homepage: https://github.com/FlutterQueen/nations_assets
issue_tracker: https://github.com/FlutterQueen/nations_assets/issues
environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  flutter_lints: ^1.0.0
  test: ^1.20.1
