/// `Spanish` assets
const esAssets = <String, Object>{
  "date": "fecha",
  "time": "tiempo",
  "enter": "entrar",
  "edit": "editar",
  "show": "mostrar",
  "delete": "borrar",
  "error": "error",
  "internet": "internet",
  "gender": {
    "this": "género",
    "male": "masculina",
    "female": "mujer",
  },
  "no": "no",
  "yes": "si",
  "confirm": "confirmar",
  "cancel": "cancelar",
  "color": "color",
  "age": "la edad",
  "key": "llave",
  "value": "valor",
  "to": "para",
  "back": "espalda",
  "save": "ahorrar",
  "add": "agregar",
  "update": "actualizar",
  "notification": "notificación",
  "search": "buscar",
  "close": "cerrar",
  "clear": "clara",
  "next": "Siguiente",
  "previous": "Previa",
  "select": "Seleccione",
  "select_all": "seleccionar todo",
  "skip": "saltar",
  "view": "vista",
  "call": "llama",
  "second": "segunda",
  "seconds": "segundos",
  "minute": "minuto",
  "minutes": "minutos",
  "hour": "hora",
  "hours": "horas",
  "day": "día",
  "days": "días",
  "week": "semana",
  "weeks": "semanas",
  "year": "Año",
  "years": "Años",
  "more": "más",
  "paste": "Pegar",
  "january": "enero",
  "february": "febrero",
  "march": "marcha",
  "april": "abril",
  "may": "Mayo",
  "june": "junio",
  "july": "julio",
  "august": "agosto",
  "september": "septiembre",
  "october": "octubre",
  "november": "noviembre",
  "december": "diciembre",
  "auth": {
    "password": "contraseña",
    "sign_in": "iniciar sesión",
    "sign_up": "inscribirse",
    "sign_out": "cerrar sesión",
  },
  "city": "ciudad",
  "all": "todos",
  "am": "am",
  "pm": "pm",
  "filter": "filtrar",
  "send": "enviar",
  "or": "o",
  "menu": "menú",
  "sort_by": "Ordenar por",
  "view_all": "ver todo",
};
