/// `French` assets
const frAssets = <String, Object>{
  "date": "Date",
  "time": "temps",
  "enter": "Entrer",
  "edit": "Éditer",
  "show": "Afficher",
  "delete": "effacer",
  "error": "Erreur",
  "internet": "l'Internet",
  "gender": {
    "this": "le genre",
    "male": "mâle",
    "female": "femelle",
  },
  "no": "non",
  "yes": "Oui",
  "confirm": "confirmer",
  "cancel": "Annuler",
  "color": "Couleur",
  "age": "âge",
  "key": "clé",
  "value": "valeur",
  "to": "à",
  "back": "retour",
  "save": "sauver",
  "add": "ajouter",
  "update": "mettre à jour",
  "notification": "notification",
  "search": "chercher",
  "close": "Fermer",
  "clear": "dégager",
  "next": "suivante",
  "previous": "précédente",
  "select": "sélectionner",
  "select_all": "tout sélectionner",
  "skip": "sauter",
  "view": "voir",
  "call": "appeler",
  "second": "seconde",
  "seconds": "secondes",
  "minute": "minute",
  "minutes": "minutes",
  "hour": "heure",
  "hours": "les heures",
  "day": "journée",
  "days": "jours",
  "week": "la semaine",
  "weeks": "semaines",
  "year": "an",
  "years": "années",
  "more": "Suite",
  "paste": "pâte",
  "january": "janvier",
  "february": "février",
  "march": "Mars",
  "april": "avril",
  "may": "peut",
  "june": "juin",
  "july": "juillet",
  "august": "août",
  "september": "septembre",
  "october": "octobre",
  "november": "novembre",
  "december": "décembre",
  "auth": {
    "password": "le mot de passe",
    "sign_in": "s'identifier",
    "sign_up": "s'inscrire",
    "sign_out": "se déconnecter",
  },
  "city": "ville",
  "all": "toute",
  "am": "un m",
  "pm": "après-midi",
  "filter": "filtre",
  "send": "envoyer",
  "or": "ou",
  "menu": "menu",
  "sort_by": "Trier par",
  "view_all": "Voir tout",
};
