/// `Turkish` assets
const TurAssets = <String, Object>{
  "date": "tarih",
  "time": "zaman",
  "enter": "girmek",
  "edit": "Düzenle",
  "show": "göstermek",
  "delete": "silmek",
  "error": "hata",
  "internet": "internet",
  "gender": {
    "this": "Cinsiyet",
    "male": "erkek",
    "female": "dişi",
  },
  "no": "Hayır",
  "yes": "Evet",
  "confirm": "teyit etmek",
  "cancel": "İptal et",
  "color": "renk",
  "age": "yaş",
  "key": "anahtar",
  "value": "değer",
  "to": "ile",
  "back": "geri",
  "save": "kayıt etmek",
  "add": "Ekle",
  "update": "Güncelleme",
  "notification": "bildirim",
  "search": "Ara",
  "close": "kapat",
  "clear": "açık",
  "next": "sonraki",
  "previous": "öncesi",
  "select": "Seçme",
  "select_all": "hepsini seç",
  "skip": "atlamak",
  "view": "görüş",
  "call": "aramak",
  "second": "ikinci",
  "seconds": "saniye",
  "minute": "dakika",
  "minutes": "dakika",
  "hour": "saat",
  "hours": "saatler",
  "day": "gün",
  "days": "günler",
  "week": "hafta",
  "weeks": "haftalar",
  "year": "yıl",
  "years": "yıllar",
  "more": "daha fazla",
  "paste": "yapıştırmak",
  "january": "Ocak ayı",
  "february": "Şubat",
  "march": "Mart",
  "april": "Nisan",
  "may": "Mayıs ayı",
  "june": "Haziran",
  "july": "Temmuz",
  "august": "Ağustos",
  "september": "Eylül",
  "october": "Ekim",
  "november": "Kasım",
  "december": "ARALIK AYI",
  "auth": {
    "password": "parola",
    "sign_in": "kayıt olmak",
    "sign_up": "üye olmak",
    "sign_out": "oturumu Kapat",
  },
  "city": "Kent",
  "all": "Tümü",
  "am": "ben",
  "pm": "akşam",
  "filter": "süzgeç",
  "send": "göndermek",
  "or": "veya",
  "menu": "Menü",
  "sort_by": "göre sırala",
  "view_all": "hepsini gör",
};
